#!/bin/sh
# Throwaway test PKI and DER CRLs for revocation checks (lib/crl.js, the runner's `tls --revocation`,
# the CLI's --revocation). EC P-256 unless noted, valid 2025-01-01 .. 2060-01-01:
#   crl_ca.pem         Example Test CRL CA, self-signed (its key stays in the work directory)
#   crl_leaf.pem       www.example.com and example.com, serial 0c1001, under the CRL CA, CRL
#                      distribution point http://crl.example.com/test-ca.crl; its key crl_leaf.key
#   crl_leaf2.pem      api.example.net, serial 0c1002, under the CRL CA (its key was not kept)
#   crl_other_ca.pem   Example Test Other CA (RSA 2048), self-signed (its key stays in the work directory)
#   crl_revoked.der    the CRL CA's CRL: 0c1001 keyCompromise (2026-09-01 12:00) and 0c1002 superseded
#                      (2026-08-15 08:30); issuing distribution point http://crl.example.com/test-ca.crl,
#                      user certificates only; CRL number 0x10; thisUpdate 2026-10-01, nextUpdate 2026-10-15
#   crl_empty.der      the same CA and distribution point, nothing revoked; CRL number 0x11, the same dates
#   crl_other.der      the Other CA's CRL (RSA, SHA-256), listing serial 0c1001 too (keyCompromise); no
#                      distribution point; the same dates
# Dev tool, needs OpenSSL 3.4+ (-not_before, -crl_lastupdate); the committed files were made with it
# and are never regenerated by the tests:
#   sh tests/fixtures/gen_crl_fixtures.sh tests/fixtures "$(mktemp -d)"
# The leaf key protects nothing: tests only.
set -e
export MSYS_NO_PATHCONV=1   # Git Bash: keep -subj '/O=...' as written
OUT=$(cd "$1" && pwd)
WORK="$2"
mkdir -p "$WORK"
cd "$WORK"
DATES='-not_before 20250101000000Z -not_after 20600101000000Z'
CRL_DATES='-crl_lastupdate 20261001000000Z -crl_nextupdate 20261015000000Z'
DP='http://crl.example.com/test-ca.crl'

cat > base.ext <<EOF
basicConstraints=critical,CA:FALSE
keyUsage=critical,digitalSignature
extendedKeyUsage=serverAuth
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid
crlDistributionPoints=URI:$DP
EOF
cp base.ext leaf.ext
printf 'subjectAltName=DNS:www.example.com,DNS:example.com\n' >> leaf.ext
cp base.ext leaf2.ext
printf 'subjectAltName=DNS:api.example.net\n' >> leaf2.ext

# The CRL CA and its two leaves.
openssl ecparam -name prime256v1 -genkey -noout -out ca.key
# shellcheck disable=SC2086
openssl req -new -x509 -key ca.key -subj '/O=Example Test PKI/CN=Example Test CRL CA' $DATES -sha256 \
  -addext 'basicConstraints=critical,CA:TRUE' -addext 'keyUsage=critical,keyCertSign,cRLSign' \
  -addext 'subjectKeyIdentifier=hash' -out crl_ca.pem
openssl ecparam -name prime256v1 -genkey -noout -out crl_leaf.key
openssl req -new -key crl_leaf.key -subj '/CN=www.example.com' -out leaf.csr
# shellcheck disable=SC2086
openssl x509 -req -in leaf.csr -CA crl_ca.pem -CAkey ca.key -set_serial 0x0c1001 $DATES -sha256 -extfile leaf.ext -out crl_leaf.pem
openssl ecparam -name prime256v1 -genkey -noout -out leaf2.key
openssl req -new -key leaf2.key -subj '/CN=api.example.net' -out leaf2.csr
# shellcheck disable=SC2086
openssl x509 -req -in leaf2.csr -CA crl_ca.pem -CAkey ca.key -set_serial 0x0c1002 $DATES -sha256 -extfile leaf2.ext -out crl_leaf2.pem
openssl verify -CAfile crl_ca.pem crl_leaf.pem crl_leaf2.pem

# `openssl ca` makes the CRLs from an index of its own, written here so the revocation times are fixed.
cat > ca.cnf <<EOF
[ ca ]
default_ca = test_ca
[ test_ca ]
database = index.txt
crlnumber = crlnumber
default_md = sha256
unique_subject = no
crl_extensions = crl_ext
[ crl_ext ]
authorityKeyIdentifier = keyid:always
issuingDistributionPoint = critical, @idp
[ idp ]
fullname = URI:$DP
onlyuser = TRUE
EOF
TAB=$(printf '\t')
printf 'R%s20600101000000Z%s260901120000Z,keyCompromise%s0C1001%sunknown%s/CN=www.example.com\n' "$TAB" "$TAB" "$TAB" "$TAB" "$TAB" > index.txt
printf 'R%s20600101000000Z%s260815083000Z,superseded%s0C1002%sunknown%s/CN=api.example.net\n' "$TAB" "$TAB" "$TAB" "$TAB" "$TAB" >> index.txt
echo 10 > crlnumber
# shellcheck disable=SC2086
openssl ca -config ca.cnf -gencrl -cert crl_ca.pem -keyfile ca.key $CRL_DATES -out revoked.pem
: > index.txt
# shellcheck disable=SC2086
openssl ca -config ca.cnf -gencrl -cert crl_ca.pem -keyfile ca.key $CRL_DATES -out empty.pem

# Another CA (RSA) whose CRL lists the leaf's serial number too.
openssl genrsa -out other.key 2048 2>/dev/null
# shellcheck disable=SC2086
openssl req -new -x509 -key other.key -subj '/O=Example Test PKI/CN=Example Test Other CA' $DATES -sha256 \
  -addext 'basicConstraints=critical,CA:TRUE' -addext 'keyUsage=critical,keyCertSign,cRLSign' \
  -addext 'subjectKeyIdentifier=hash' -out crl_other_ca.pem
sed -e 's/^issuingDistributionPoint.*//' ca.cnf > other.cnf
printf 'R%s20600101000000Z%s260901120000Z,keyCompromise%s0C1001%sunknown%s/CN=www.example.com\n' "$TAB" "$TAB" "$TAB" "$TAB" "$TAB" > index.txt
echo 01 > crlnumber
# shellcheck disable=SC2086
openssl ca -config other.cnf -gencrl -cert crl_other_ca.pem -keyfile other.key $CRL_DATES -out other.pem

openssl crl -in revoked.pem -outform DER -out crl_revoked.der
openssl crl -in empty.pem -outform DER -out crl_empty.der
openssl crl -in other.pem -outform DER -out crl_other.der
openssl crl -inform DER -in crl_revoked.der -CAfile crl_ca.pem -noout
openssl crl -inform DER -in crl_other.der -CAfile crl_other_ca.pem -noout
cp crl_ca.pem crl_leaf.pem crl_leaf.key crl_leaf2.pem crl_other_ca.pem crl_revoked.der crl_empty.der crl_other.der "$OUT/"
