#!/bin/sh
# Throwaway test PKI for the CLI's bundle-check tests (valid 2025-01-01 .. 2050-01-01): a
# root and an intermediate CA (EC P-256), an RSA 2048 leaf for www.example.com / example.com
# and an EC P-256 leaf for api.example.net, both issued by the intermediate, with their keys
# in every format bundle-check reads and their CSRs, and a self-signed CA:TRUE certificate
# for www.example.com without subjectAltName. Dev tool, needs OpenSSL 3.4+ (-not_before);
# the committed files were made with it and are never regenerated by the tests:
#   sh tests/fixtures/gen_bundle_fixtures.sh tests/fixtures "$(mktemp -d)"
# The CA keys and the self-signed certificate's key stay in the work directory. The leaf
# keys protect nothing: tests only.
set -e
OUT="$1"
WORK="$2"
mkdir -p "$WORK"
cd "$WORK"
DATES='-not_before 20250101000000Z -not_after 20500101000000Z'

cat > ca.ext <<EOF
basicConstraints=critical,CA:TRUE
keyUsage=critical,keyCertSign,cRLSign
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid
EOF
cat > rsa.ext <<EOF
basicConstraints=critical,CA:FALSE
keyUsage=critical,digitalSignature,keyEncipherment
extendedKeyUsage=serverAuth
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid
authorityInfoAccess=caIssuers;URI:http://ca.example.com/bundle-inter.crt
subjectAltName=DNS:www.example.com,DNS:example.com
EOF
cat > ec.ext <<EOF
basicConstraints=critical,CA:FALSE
keyUsage=critical,digitalSignature
extendedKeyUsage=serverAuth
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid
subjectAltName=DNS:api.example.net
EOF

# The root, and the intermediate it issued.
openssl ecparam -name prime256v1 -genkey -noout -out root.key
# shellcheck disable=SC2086
openssl req -new -x509 -key root.key -subj '/O=Example Test PKI/CN=Example Test Bundle Root CA' \
  $DATES -sha256 -extensions v3_ca -addext 'basicConstraints=critical,CA:TRUE' \
  -addext 'keyUsage=critical,keyCertSign,cRLSign' -out bundle_root.pem
openssl ecparam -name prime256v1 -genkey -noout -out inter.key
openssl req -new -key inter.key -subj '/O=Example Test PKI/CN=Example Test Bundle Intermediate CA' -out inter.csr
# shellcheck disable=SC2086
openssl x509 -req -in inter.csr -CA bundle_root.pem -CAkey root.key -set_serial 0x0b0b01 $DATES \
  -sha256 -extfile ca.ext -out bundle_inter.pem

# The RSA leaf: its key as PKCS#8, PKCS#1 and encrypted PKCS#8 (password "bundle-test"), its CSR.
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out bundle_leaf.key
openssl pkey -in bundle_leaf.key -traditional -out bundle_leaf.rsa.key
openssl pkcs8 -topk8 -in bundle_leaf.key -v2 aes-256-cbc -passout pass:bundle-test -out bundle_leaf.enc.key
openssl req -new -key bundle_leaf.key -subj '/CN=www.example.com' \
  -addext 'subjectAltName=DNS:www.example.com,DNS:example.com' -out bundle_leaf.csr
# shellcheck disable=SC2086
openssl x509 -req -in bundle_leaf.csr -CA bundle_inter.pem -CAkey inter.key -set_serial 0x0b0b02 \
  $DATES -sha256 -extfile rsa.ext -out bundle_leaf.pem

# The EC leaf: its key as SEC1 with and without the public key, its CSR.
openssl ecparam -name prime256v1 -genkey -noout -out bundle_ec_leaf.key
openssl ec -in bundle_ec_leaf.key -no_public -out bundle_ec_leaf.nopub.key
openssl req -new -key bundle_ec_leaf.key -subj '/CN=api.example.net' \
  -addext 'subjectAltName=DNS:api.example.net' -out bundle_ec_leaf.csr
# shellcheck disable=SC2086
openssl x509 -req -in bundle_ec_leaf.csr -CA bundle_inter.pem -CAkey inter.key -set_serial 0x0b0b03 \
  $DATES -sha256 -extfile ec.ext -out bundle_ec_leaf.pem

# Another key and a CSR made with it (neither belongs to a certificate here).
openssl genpkey -algorithm RSA -pkeyopt rsa_keygen_bits:2048 -out bundle_other.key
openssl req -new -key bundle_other.key -subj '/CN=www.example.com' \
  -addext 'subjectAltName=DNS:www.example.com,DNS:shop.example.com' -out bundle_other.csr

# What `openssl req -x509 -newkey ... -nodes -subj /CN=www.example.com` makes with OpenSSL's
# default configuration: self-signed and CA:TRUE, without keyUsage or subjectAltName.
cat > selfsigned.cnf <<EOF
[req]
distinguished_name=dn
x509_extensions=v3_ca
[dn]
[v3_ca]
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid:always,issuer
basicConstraints=critical,CA:true
EOF
# shellcheck disable=SC2086
openssl req -x509 -config selfsigned.cnf -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 -nodes \
  -keyout selfsigned.key -subj '/CN=www.example.com' $DATES -sha256 -out bundle_selfsigned_ca.pem

# A CA bundle as some CAs ship it: the root first, then the intermediate.
cat bundle_root.pem bundle_inter.pem > bundle_ca_reversed.pem

cp bundle_root.pem bundle_inter.pem bundle_leaf.pem bundle_leaf.key bundle_leaf.rsa.key \
  bundle_leaf.enc.key bundle_leaf.csr bundle_ec_leaf.pem bundle_ec_leaf.key bundle_ec_leaf.nopub.key \
  bundle_ec_leaf.csr bundle_other.key bundle_other.csr bundle_ca_reversed.pem \
  bundle_selfsigned_ca.pem "$OUT/"
