#!/bin/sh
# Throwaway test PKI for the chain check of the CLI's --tls-audit (tests/python/test_tls_audit_fleet.py):
# a chain sent with an expired cross-signed copy of the root a client trusts, as the AddTrust (2020)
# and DST Root CA X3 (2024) cross-signs expired. EC P-256, valid 2025-01-01 .. 2060-01-01 unless noted:
#   cross_root.pem         Example Test Cross Root, self-signed (the test client trusts it)
#   cross_old_root.pem     Example Test Cross Old Root, self-signed (valid from 2010)
#   cross_root_by_old.pem  the Cross Root's name and key cross-signed by the Old Root, expired on 2024-09-30
#   cross_inter.pem        Example Test Cross Issuing CA, under the Cross Root
#   cross_inter_old.pem    the same CA (name and key) as first issued, expired on 2024-09-30
#   cross_leaf.pem         www.example.com and example.com, under the Issuing CA, with its key cross_leaf.key
# Dev tool, needs OpenSSL 3.4+ (-not_before); the committed files were made with it and are never
# regenerated by the tests:
#   sh tests/fixtures/gen_cross_fixtures.sh tests/fixtures "$(mktemp -d)"
# The CA keys stay in the work directory. The leaf key protects nothing: tests only.
set -e
export MSYS_NO_PATHCONV=1   # Git Bash: keep -subj '/O=...' as written
OUT=$(cd "$1" && pwd)
WORK="$2"
mkdir -p "$WORK"
cd "$WORK"
DATES='-not_before 20250101000000Z -not_after 20600101000000Z'
EXPIRED='-not_after 20240930000000Z'

cat > ca.ext <<EOF
basicConstraints=critical,CA:TRUE
keyUsage=critical,keyCertSign,cRLSign
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid
EOF
cat > leaf.ext <<EOF
basicConstraints=critical,CA:FALSE
keyUsage=critical,digitalSignature
extendedKeyUsage=serverAuth
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid
subjectAltName=DNS:www.example.com,DNS:example.com
EOF
for key in root old inter; do
  openssl ecparam -name prime256v1 -genkey -noout -out $key.key
done
openssl ecparam -name prime256v1 -genkey -noout -out cross_leaf.key

# The two roots, and the Cross Root's name and key under the Old Root (expired).
# shellcheck disable=SC2086
openssl req -new -x509 -key root.key -subj '/O=Example Test PKI/CN=Example Test Cross Root' $DATES \
  -sha256 -addext 'basicConstraints=critical,CA:TRUE' -addext 'keyUsage=critical,keyCertSign,cRLSign' \
  -out cross_root.pem
openssl req -new -x509 -key old.key -subj '/O=Example Test PKI/CN=Example Test Cross Old Root' \
  -not_before 20100101000000Z -not_after 20600101000000Z -sha256 \
  -addext 'basicConstraints=critical,CA:TRUE' -addext 'keyUsage=critical,keyCertSign,cRLSign' \
  -out cross_old_root.pem
openssl req -new -key root.key -subj '/O=Example Test PKI/CN=Example Test Cross Root' -out root.csr
# shellcheck disable=SC2086
openssl x509 -req -in root.csr -CA cross_old_root.pem -CAkey old.key -set_serial 0x0c0c01 \
  -not_before 20150101000000Z $EXPIRED -sha256 -extfile ca.ext -out cross_root_by_old.pem

# The Issuing CA under the Cross Root, and its first copy (the same name and key, expired).
openssl req -new -key inter.key -subj '/O=Example Test PKI/CN=Example Test Cross Issuing CA' -out inter.csr
# shellcheck disable=SC2086
openssl x509 -req -in inter.csr -CA cross_root.pem -CAkey root.key -set_serial 0x0c0c02 $DATES \
  -sha256 -extfile ca.ext -out cross_inter.pem
# shellcheck disable=SC2086
openssl x509 -req -in inter.csr -CA cross_root.pem -CAkey root.key -set_serial 0x0c0c03 \
  -not_before 20200101000000Z $EXPIRED -sha256 -extfile ca.ext -out cross_inter_old.pem

# The leaf.
openssl req -new -key cross_leaf.key -subj '/CN=www.example.com' -out leaf.csr
# shellcheck disable=SC2086
openssl x509 -req -in leaf.csr -CA cross_inter.pem -CAkey inter.key -set_serial 0x0c0c04 $DATES \
  -sha256 -extfile leaf.ext -out cross_leaf.pem

openssl verify -CAfile cross_root.pem -untrusted cross_inter.pem cross_leaf.pem
cp cross_root.pem cross_old_root.pem cross_root_by_old.pem cross_inter.pem cross_inter_old.pem \
  cross_leaf.pem cross_leaf.key "$OUT/"
