#!/bin/sh
# Throwaway test PKI for the CLI's ORIGIN_CERT / PRIVATE_CERT tests (EC P-256, valid
# 2025-01-01 .. 2050-01-01). Dev tool, needs OpenSSL 3.4+ (-not_before); the committed files
# were made with it and are never regenerated by the tests:
#   sh tests/fixtures/gen_cli_kind_fixtures.sh tests/fixtures "$(mktemp -d)"
# The CA keys stay in the work directory; only the leaves carry a key (the tests serve them).
set -e
OUT="$1"
WORK="$2"
mkdir -p "$WORK"
cd "$WORK"
DATES='-not_before 20250101000000Z -not_after 20500101000000Z'

cat > leaf.ext <<EOF
basicConstraints=critical,CA:FALSE
keyUsage=critical,digitalSignature
extendedKeyUsage=serverAuth
subjectKeyIdentifier=hash
authorityKeyIdentifier=keyid
subjectAltName=DNS:*.wild.example.net,DNS:wild.example.net
EOF

mkca() {  # name subject
  openssl ecparam -name prime256v1 -genkey -noout -out "$1.key"
  # shellcheck disable=SC2086
  openssl req -new -x509 -key "$1.key" -subj "$2" $DATES -sha256 -extensions v3_ca \
    -addext 'basicConstraints=critical,CA:TRUE' -addext 'keyUsage=critical,keyCertSign,cRLSign' \
    -out "$1.pem"
}
mkleaf() {  # name subject ca
  openssl ecparam -name prime256v1 -genkey -noout -out "$1.key"
  openssl req -new -key "$1.key" -subj "$2" -out "$1.csr"
  # shellcheck disable=SC2086
  openssl x509 -req -in "$1.csr" -CA "$3.pem" -CAkey "$3.key" \
    -set_serial "0x$(openssl rand -hex 8)" $DATES -sha256 -extfile leaf.ext -out "$1.pem"
}

# A CA nobody lists with --private-ca: what it issues is kind "other", like a public CA.
mkca public_ca '/O=Example Test PKI/CN=Example Public Test CA'
mkleaf cli_public_wild '/CN=*.wild.example.net' public_ca
# The Cloudflare Origin CA's issuer DN (it has no CN) on a throwaway key - not Cloudflare's.
mkca origin_ca '/C=US/O=CloudFlare, Inc./OU=CloudFlare Origin SSL Certificate Authority/L=San Francisco/ST=California'
mkleaf cli_origin_wild '/O=CloudFlare, Inc./OU=CloudFlare Origin CA/CN=CloudFlare Origin Certificate' origin_ca
# An internal CA, a leaf it issued, and a CA with the same name on another key.
mkca cli_private_ca '/O=Example Corp/CN=Example Internal Test CA'
mkleaf cli_private_wild '/CN=*.wild.example.net' cli_private_ca
mkca cli_private_ca_rekeyed '/O=Example Corp/CN=Example Internal Test CA'

cp cli_public_wild.pem cli_public_wild.key cli_origin_wild.pem cli_origin_wild.key \
  cli_private_wild.pem cli_private_wild.key cli_private_ca.pem cli_private_ca_rekeyed.pem "$OUT/"
